version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - db:/data/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=user_manager_api
    networks:
      - db
    restart: unless-stopped
  user-manager-api:
    container_name: user-manager-api
    image: aleh1s/user-manager-api:latest
    ports:
      - '8088:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user_manager_api
    networks:
      - db
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
    driver: local
