spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/user_manager_api
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

server:
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        security: DEBUG